# Yakka Dee S1 前5集 中文字典（覆盖全部独特台词）
D = {
 "Dee? Where are you? I've seen her!":"迪伊？你在哪儿？我看见她了！",
 "- Dee! Where are you? - I've seen her.":"迪伊！你在哪儿？——我看见她了。",
 "- Dee! Where are you? - I've seen her. Over there!":"迪伊！你在哪儿？——我看见她了。在那边！",
 "Over there!":"在那边！",
 "Over there.":"在那边。",
 "Dee!":"迪伊！",
 "SHE LAUGHS":"【她笑了】",
 "SHE LAUGHS Tiny dog.":"【她笑了】小狗。",
 "Book! SHE LAUGHS":"书！【她笑了】",
 "LAUGHTER":"【笑声】",
 "# Yakka Dee, Yakka Dee":"【歌曲】雅卡迪，雅卡迪",
 "# Yakka Dee Yakka Dee":"【歌曲】雅卡迪，雅卡迪",
 "# My name is Dee, I like to talk":"【歌曲】我叫迪伊，我喜欢说话",
 "# My name is Dee I like to talk":"【歌曲】我叫迪伊，我喜欢说话",
 "# They call me Yakka Dee":"【歌曲】他们叫我雅卡迪",
 "- # They call me Yakka Dee - Dee!":"【歌曲】他们叫我雅卡迪——迪伊！",
 "- # They call me Yakka Dee - # Dee!":"【歌曲】他们叫我雅卡迪——迪伊！",
 "# Talking makes us happy":"【歌曲】说话让我们快乐",
 "- # Will you yakka-yak with me? - Me!":"【歌曲】你愿意和我一起说说说吗？——我愿意！",
 "# Will you yakka-yak with me?":"【歌曲】你愿意和我一起说说说吗？",
 "# Will you Yakka Yak with me? - Me!":"【歌曲】你愿意和我一起说说说吗？——我愿意！",
 "# Bus, mouse":"【歌曲】巴士、老鼠",
 "# Apple, house":"【歌曲】苹果、房子",
 "# Bus! - Bus! - Mouse! - Mouse!":"【歌曲】巴士！巴士！老鼠！老鼠！",
 "# Apple! - Apple! - House! - House!":"【歌曲】苹果！苹果！房子！房子！",
 "# Yakka yak":"【歌曲】说说说",
 "# Yakky-yak":"【歌曲】说说说",
 "- # Yakky-yak - Yakka Dee":"【歌曲】说说说——雅卡迪",
 "# I know you can":"【歌曲】我知道你行",
 "- # I know you can - Yakka Dee":"【歌曲】我知道你行——雅卡迪",
 "# You'll get filled up":"【歌曲】你会饱饱的",
 "- # You'll get filled up - Yakka Dee":"【歌曲】你会饱饱的——雅卡迪",
 "# With whizz, pop, bang":"【歌曲】伴随着嗞、啵、嘭",
 "# With whizz, pop, bang!":"【歌曲】伴随着嗞、啵、嘭",
 "# Yakka Dee, Yakka Dee":"【歌曲】雅卡迪，雅卡迪",
 "# Yakka Dee Yakka dee":"【歌曲】雅卡迪，雅卡迪",
 "# Let's all Yakka Dee! #":"【歌曲】大家一起雅卡迪吧！",
 "# Let's all yakka-dee! #":"【歌曲】大家一起雅卡迪吧！",
 "# La-la-la-la-la-la-la. #":"【歌曲】啦—啦—啦—啦—啦—啦",
 "What will our yakka be today?":"今天我们学什么词呢？",
 "What will our Yakka be today?":"今天我们学什么词呢？",
 # 选择环节
 "Dog...duck...lion...mouse.":"狗……鸭子……狮子……老鼠。",
 "Worm, ball, hat, boots.":"虫子、球、帽子、靴子。",
 "Bike, car, boat, bus.":"自行车、汽车、船、巴士。",
 "House! Book! Bed! Cup!":"房子！书！床！杯子！",
 "Apple, peas, banana, beans.":"苹果、豌豆、香蕉、豆子。",
 "DRUM ROLL":"【鼓声】",
 "CYMBAL CRASH":"【镲声】",
 # Dog 集
 "Dog!":"狗！","Dog.":"狗。","Dog. Woof! Woof!":"狗。汪！汪！",
 'You say "dog".':"你说“狗”。","You say dog.":"你说“狗”。",
 "Hooray!":"万岁！","ALL: Hooray!":"齐：万岁！",
 "I'll help you. Let's go.":"我来帮你。我们走吧。",
 "I'll help you. Let's go!":"我来帮你。我们走吧！",
 "Big dog.":"大狗。","Tiny dog.":"小狗。","Hello!":"你好！",
 "Fluffy dog.":"毛茸茸的狗。","REALLY fluffy dog!":"超级毛茸茸的狗！",
 "DOG WHINES":"【狗呜呜叫】","DOG BARKS":"【狗叫】",
 "ALL: Dog!":"齐：狗！","Good dog.":"好狗狗。","Yay!":"耶！","Yeah!":"耶！",
 "Yay! Catching dog.":"耶！接球的狗。","Catching dog!":"接球的狗！",
 "Whoops!":"哎呀！","Spotty dog.":"斑点狗。",
 "Sitting dog.":"坐着的狗。","Sitting dog. DOG BARKS":"坐着的狗。【狗叫】",
 "Fast dog!":"飞快的狗！",
 "DOG PANTS Happy dog.":"【狗喘气】快乐的狗。","BOTH: Dog!":"合：狗。","BOTH: Dog.":"合：狗。",
 "He-he! Sunny dog.":"嘿嘿！阳光下的狗。",
 "Sausage dog!":"腊肠狗！","Dancing dog.":"跳舞的狗。",
 "Woof-woof! I'm a dog.":"汪汪！我是一只狗。",
 "Yakka-yak. I know you can. It will fill you up with whizz, pop, bang!":"说说说。我知道你行。它会让你吃饱，嗞、啵、嘭！",
 "More dog. Let's go again.":"更多狗。我们再试一次。",
 "Yeah! Yakka Dee!":"耶！雅卡迪！",
 "You did it. Yeah!":"你做到了。耶！",
 "- Dog. - Dog. - Dog. - ALL: Dog!":"狗。——狗。——狗。——齐：狗！",
 # Book 集
 "House!":"房子！","Book!":"书！","Bed!":"床！","Cup!":"杯子！",
 "- Book! - Hooray!":"书！——万岁！",
 'Book! You say "book".':"书！你说“书”。","Book.":"书。",
 'You say "book".':"你说“书”。",
 "New book.":"新书。","Old book.":"旧书。","Wow! Gold book.":"哇！金色的书。",
 "Bedtime book.":"睡前故事书。","Bath-time book.":"洗澡时的书。",
 "Laugh-time book!":"逗笑的书！","Laugh-time book.":"逗笑的书。","Books!":"书！",
 "Flap book.":"翻翻书。","Scrapbook.":"剪贴簿。",
 "Take-it-back book.":"要还回去的书。","Wow! Book.":"哇！书。",
 "Noisy book!":"吵闹的书！","Feely book.":"触摸书。","Wheelie book.":"轮子书。",
 "Wheelie book. Choo-choo!":"轮子书。哐哐！","Choo-choo!":"哐哐！",
 "I'm a book.":"我是一本书。","I'm a book!":"我是一本书！",
 "Yakka-yak. I know you can. It will fill you up with whizz, pop, bang.":"说说说。我知道你行。它会让你吃饱，嗞、啵、嘭。",
 "More book! Let's go again.":"更多书！我们再试一次。",
 "Whee!":"哇！","Ta-da.":"哒哒。","Oh!":"哦！",
 "Book! Yakka-yak.":"书！说说说。",
 "I know you can. It will fill you up with whizz, pop, bang.":"我知道你行。它会让你吃饱，嗞、啵、嘭。",
 "- You did it! Yeah! - Book.":"你做到了！耶！——书。",
 "- Book. - Book. - Book!":"书。——书。——书！",
 # Boots 集
 "Worm,":"虫子、","ball,":"球、","hat,":"帽子、","boots.":"靴子。",
 "Boots!":"靴子！","You say boots.":"你说“靴子”。","Boots.":"靴子。",
 "I'll help you.":"我来帮你。","Let's go!":"我们走吧！",
 "Blue boots.":"蓝色的靴子。","New boots.":"新靴子。","Brr!":"呃！（好冷）",
 "Fluffy boots.":"毛茸茸的靴子。","- BOTH: - Welly boots!":"合：雨靴！",
 "Ah!":"啊！","Smelly boots!":"臭臭的靴子！","Stuck boot.":"卡住的靴子。",
 "Puddle boots.":"踩水坑的靴子。","Muddle boots.":"乱糟糟的靴子。",
 "Give someone a cuddle boots! Aww!":"给人一个拥抱的靴子！哎呀！",
 "Give someone a cuddle boots.":"给人一个拥抱的靴子。","Aww!":"哎呀！",
 "Monster boots.":"怪兽靴子。","Rawr!":"嗷！","Puss in boots.":"穿靴子的猫。",
 "Yee-haw!":"哟哈！","I'm a cowboy boot!":"我是一只牛仔靴！",
 "- Boots! - Boots! - Stomp, stomp, stomp! - Stomp, stomp, stomp!":"靴子！——靴子！——跺脚，跺脚，跺脚！——跺脚，跺脚，跺脚！",
 "- ALL: - Hooray!":"齐：万岁！",
 "It will fill you up with whizz, pop, bang!":"它会让你吃饱，嗞、啵、嘭！",
 "More boots.":"更多靴子。","Boo!":"嘘！",
 "- Boots. - Boots. - Boots.":"靴子。——靴子。——靴子。","- ALL: - Boots!":"齐：靴子！",
 # Bike 集
 "Bike.":"自行车。","Bike. You say bike.":"自行车。你说自行车。",
 "- KIDS: - Hooray!":"孩子们：万岁！","You say bike.":"你说“自行车”。",
 "Grown-up bike.":"大人的自行车。","Woo! Tiny bike.":"呜！小小的自行车。",
 "My new green and shiny bike!":"我新的绿色闪亮的自行车！","Bike!":"自行车！",
 "Splashy bike.":"溅水的自行车。","Wow, flashy bike.":"哇，亮闪闪的自行车。",
 "TYRES SQUEAL":"【轮胎尖叫】","Superfast and dashy bike.":"超级快的飞驰自行车。",
 "- KIDS: - Bike!":"孩子们：自行车！","Shopping bike.":"购物自行车。",
 "Hopping bike. Wow.":"蹦跳的自行车。哇。","Hopping bike. Wowee.":"蹦跳的自行车。哇哦。",
 "Honk, honk! Ding-a-ling-a-bike.":"嘀嘀！叮铃铃的自行车。",
 "BIKE BELL RINGS":"【自行车铃响】",
 "- Uphill bike. - Hmm.":"上坡的自行车。——嗯。",
 "- Downhill bike. - Huh? - Whee!":"下坡的自行车。——哈？——哇！",
 "Bikes.":"自行车。","Yeah! Yeah, yeah, yeah, yeah!":"耶！耶耶耶耶！",
 "- KIDS: - Hurray!":"孩子们：好耶！",
 "Yakka Yak, I know you can.":"雅卡呀呀，我知道你行。",
 "More bike.":"更多自行车。","Let's go again.":"我们再试一次。",
 "- Bike. - Bike. - Bike.":"自行车。——自行车。——自行车。",
 "- KIDS: - Bike.":"孩子们：自行车。",
 # Banana 集专属
 "Banana!":"香蕉！","Banana.":"香蕉。",'Banana! You say banana.':"香蕉！你说香蕉。",
 'You say banana.':"你说香蕉。","Yellow banana.":"黄色的香蕉。",
 "Peel a banana!":"剥香蕉！","Bits of banana.":"一小块香蕉。",
 "I'm a banana!":"我是一根香蕉！","Yummy banana!":"美味的香蕉！",
 "Big banana.":"大香蕉。","Ooh! Where is the banana?":"哦！香蕉在哪里？",
 "Banana?":"香蕉？","Ooh, mushy banana!":"哦，软乎乎的香蕉！",
 "Whooshy banana!":"哦，旋转的香蕉！","BOTH: Pyjama banana!":"合：睡衣香蕉！",
 "BANANA PHONE RINGS":"【香蕉电话响了】","Ring banana.":"响铃的香蕉。",
 "Hello?":"喂？","King banana.":"香蕉国王。","Yes!":"是的！",
 "Blub, blub. Swim banana!":"咕噜咕噜。游泳的香蕉！","ALL: Go bananas!":"齐：疯狂吧！",
 "Yakka Yak! I know you can!":"雅卡呀呀！我知道你能行！",
 "It will fill you up,":"它会让你吃饱，","with whizz, pop, bang!":"嗞、啵、嘭！",
 "More banana!":"更多香蕉！","Let's go again!":"我们再来一次！","Oops!":"哎呀！",
 "Here's the banana!":"香蕉在这里！","Ooh, yeah, banana!":"哦，耶，香蕉！",
 "King banana, yeah!":"香蕉国王，耶！","Yakka Dee!":"雅卡迪！",
 "You did it, yeah!":"你做到了，耶！","- Banana! - Banana! - Banana!":"——香蕉！——香蕉！——香蕉！",
 "ALL: Banana!":"齐：香蕉！","Goodbye!":"再见！","Ring banana!":"响铃的香蕉！",
}

def tr(t):
    if t in D:
        return D[t]
    if '#' in t:
        return "【歌曲】" + t.replace('#', '').strip()
    if t.isupper():
        return "【" + t + "】"
    return "（待翻译）"
